export const DEFAULT_MAX_RETRIES = 3
export const DEFAULT_INITIAL_BACKOFF_MS = 1000
export const DEFAULT_BACKOFF_MULTIPLIER = 2
export const DEFAULT_TIMEOUT_MS = 15000
export const DEFAULT_TIMEOUT_MULTIPLIER = 1.5
